from flask import Flask
from .settings import environments
from .db import db
from flask_alembic import Alembic

# Import all exported models so Alembic autogenerated migrations work
from .models import *


def create_app(config_environment):
    app = Flask('videostore')

    config_object = environments[config_environment]()
    config_object.init_app(app)

    db.init_app(app)

    # Initialize flask-alembic
    alembic = Alembic()
    alembic.init_app(app)

    return app
